USE [master]
GO
/****** Object:  Database [JungleChess]    Script Date: 2/7/2023 12:43:13 PM ******/
CREATE DATABASE [JungleChess]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JungleChess', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\JungleChess_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JungleChess_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\JungleChess_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [JungleChess] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JungleChess].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JungleChess] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JungleChess] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JungleChess] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JungleChess] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JungleChess] SET ARITHABORT OFF 
GO
ALTER DATABASE [JungleChess] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JungleChess] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JungleChess] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JungleChess] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JungleChess] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JungleChess] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JungleChess] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JungleChess] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JungleChess] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JungleChess] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JungleChess] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JungleChess] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JungleChess] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JungleChess] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JungleChess] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JungleChess] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JungleChess] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JungleChess] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JungleChess] SET  MULTI_USER 
GO
ALTER DATABASE [JungleChess] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JungleChess] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JungleChess] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JungleChess] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JungleChess] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JungleChess] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [JungleChess] SET QUERY_STORE = ON
GO
ALTER DATABASE [JungleChess] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [JungleChess]
GO
/****** Object:  Table [dbo].[User]    Script Date: 2/7/2023 12:43:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[email] [varchar](100) NULL,
	[description] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[createUser]    Script Date: 2/7/2023 12:43:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[createUser]
	@username VARCHAR(50),
	@email VARCHAR(100),
	@description VARCHAR(300)
AS
	INSERT INTO [User] (username, email, description)
	VALUES (@username, @email, @description);
	
	SELECT SCOPE_IDENTITY() AS id;
GO
/****** Object:  StoredProcedure [dbo].[getAllUsers]    Script Date: 2/7/2023 12:43:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[getAllUsers]
AS
	SELECT * FROM [User];
GO
USE [master]
GO
ALTER DATABASE [JungleChess] SET  READ_WRITE 
GO